apiVersion: v1
kind: ConfigMap
metadata:
  name: lifesub-web-config
  namespace: kros235-lifesub-ns
data:
  MEMBER_URL: "http:///kros235.20.249.184.228.nip.io/api/auth"
  MYSUB_URL: "http://kros235.20.249.184.228.nip.io/api/mysub"
  RECOMMEND_URL: "http://kros235.20.249.184.228.nip.io/api/recommend"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: runtime-env-config
  namespace: kros235-lifesub-ns
data:
  runtime-env.js: |
    window.__runtime_config__ = {
      MEMBER_URL: 'http://kros235.20.249.184.228.nip.io/api/auth',
      MYSUB_URL: 'http://kros235.20.249.184.228.nip.io/api/mysub',
      RECOMMEND_URL: 'http://kros235.20.249.184.228.nip.io/api/recommend'
    };
